# Generated by Django 5.2.16 on 2026-07-18 15:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importance_threshold', models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('reminder_notifications_enabled', models.BooleanField(default=True)),
                ('notify_categories', models.JSONField(blank=True, default=list)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en', max_length=16)),
                ('voice_language', models.CharField(default='en', max_length=16)),
                ('tts_voice', models.CharField(default='alloy', max_length=64)),
                ('digest_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='never', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('importance_threshold__gte', 0), ('importance_threshold__lte', 100)), name='pref_importance_0_100')],
            },
        ),
    ]
