# Generated by Django 5.2.16 on 2026-07-18 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='active', max_length=16)),
                ('language', models.CharField(default='en', max_length=16)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_interaction_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_conversations',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'status', '-last_interaction_at'], name='voice_user_active_idx')],
            },
        ),
    ]
