# Generated by Django 5.2.16 on 2026-07-18 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_message_id', models.CharField(max_length=255)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.TextField(blank=True)),
                ('sender', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('recipients', models.JSONField(default=list)),
                ('cc_recipients', models.JSONField(blank=True, default=list)),
                ('bcc_recipients', models.JSONField(blank=True, default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_accounts.emailaccount')),
            ],
            options={
                'db_table': 'emails',
                'ordering': ('-received_at', '-created_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['account', '-received_at'], name='email_acct_recv_idx'), models.Index(fields=['account', 'thread_id'], name='email_acct_thread_idx'), models.Index(fields=['account', 'is_read', '-received_at'], name='email_read_recv_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'provider_message_id'), name='uniq_account_provider_msg')],
            },
        ),
    ]
