# Generated by Django 5.2.16 on 2026-07-18 15:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#64748B', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null for a system category; set for a private user category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_categories',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('importance_score', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('action_required', models.BooleanField(db_index=True, default=False)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('phishing_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reasoning', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=32)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='intelligence.aicategory')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='emails.email')),
            ],
            options={
                'db_table': 'ai_summaries',
                'ordering': ('-processed_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['importance_score', '-processed_at'], name='ai_importance_idx'), models.Index(fields=['action_required', 'deadline'], name='ai_action_deadline_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('importance_score__gte', 0), ('importance_score__lte', 100)), name='ai_importance_0_100'), models.CheckConstraint(condition=models.Q(('phishing_score__gte', 0), ('phishing_score__lte', 100)), name='ai_phishing_0_100'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ai_confidence_0_1')],
            },
        ),
    ]
