# Generated by Django 5.2.16 on 2026-07-19 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='sender_priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='Learned priority of the sender for this user.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='aisummary',
            constraint=models.CheckConstraint(condition=models.Q(('sender_priority__gte', 0), ('sender_priority__lte', 100)), name='ai_sender_priority_0_100'),
        ),
    ]
