# Generated by Django 5.2.16 on 2026-07-18 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail')], default='gmail', max_length=32)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('encryption_key_version', models.PositiveSmallIntegerField(default=1)),
                ('oauth_scopes', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('active', 'Active'), ('reauth_required', 'Reauthorization required'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], db_index=True, default='pending', max_length=32)),
                ('sync_cursor', models.CharField(blank=True, max_length=512)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_accounts',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'sync_status'], name='email_acct_sync_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'provider_account_id'), name='uniq_user_provider_account'), models.UniqueConstraint(fields=('user', 'provider', 'email_address'), name='uniq_user_provider_email')],
            },
        ),
    ]
