# Generated by Django 5.2.16 on 2026-07-19 17:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSuggestion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_type', models.CharField(choices=[('meeting_reminder', 'Meeting reminder'), ('deadline_reminder', 'Deadline reminder'), ('reply_suggestion', 'Reply suggestion'), ('follow_up_reminder', 'Follow-up reminder'), ('payment_reminder', 'Payment reminder'), ('travel_reminder', 'Travel reminder'), ('interview_reminder', 'Interview reminder'), ('government_deadline', 'Government deadline'), ('hospital_appointment', 'Hospital appointment'), ('visa_reminder', 'Visa reminder'), ('package_delivery', 'Package delivery'), ('bill_due', 'Bill due'), ('task_extraction', 'Task extraction'), ('calendar_event', 'Calendar event'), ('spam_warning', 'Spam warning'), ('phishing_warning', 'Phishing warning')], db_index=True, max_length=32)),
                ('recommended_action', models.CharField(choices=[('none', 'No action'), ('reply', 'Reply'), ('generate_reply', 'Generate reply'), ('summarize', 'Summarize'), ('translate', 'Translate'), ('archive', 'Archive'), ('mark_important', 'Mark important'), ('create_reminder', 'Create reminder'), ('add_to_calendar', 'Add to calendar'), ('call_sender', 'Call sender'), ('open_attachment', 'Open attachment'), ('review_security', 'Review security')], default='none', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shown', 'Shown'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('completed', 'Completed'), ('expired', 'Expired'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=16)),
                ('delivery_method', models.CharField(choices=[('none', 'Do nothing'), ('in_app', 'In-app suggestion'), ('push', 'Push notification'), ('popup', 'Popup'), ('voice', 'Speak')], default='in_app', max_length=16)),
                ('interruption_priority', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reason', models.TextField()),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('deduplication_key', models.CharField(max_length=64)),
                ('semantic_key', models.CharField(db_index=True, max_length=255)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='decision_engine', max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_suggestions', to='emails.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_suggestions',
                'ordering': ('-interruption_priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('helpful', 'Helpful'), ('not_helpful', 'Not helpful'), ('incorrect', 'Incorrect')], db_index=True, max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='proactive_assistant.assistantsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestion_feedback',
                'ordering': ('-occurred_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('created', 'Created'), ('presented', 'Presented'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('completed', 'Completed'), ('expired', 'Expired'), ('suppressed', 'Suppressed')], db_index=True, max_length=16)),
                ('channel', models.CharField(choices=[('none', 'Do nothing'), ('in_app', 'In-app suggestion'), ('push', 'Push notification'), ('popup', 'Popup'), ('voice', 'Speak')], default='none', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='proactive_assistant.assistantsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_suggestion_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestion_history',
                'ordering': ('-occurred_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('behavior_type', models.CharField(choices=[('email_opened', 'Email opened'), ('email_archived', 'Email archived'), ('email_replied', 'Email replied'), ('email_ignored', 'Email ignored'), ('suggestion_accepted', 'Suggestion accepted'), ('suggestion_dismissed', 'Suggestion dismissed'), ('voice_summary_requested', 'Voice summary requested'), ('language_selected', 'Language selected')], db_index=True, max_length=32)),
                ('target', models.CharField(blank=True, db_index=True, max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_behaviors', to='emails.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behaviors',
                'ordering': ('-occurred_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(max_length=191)),
                ('value', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(default='observed_behavior', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_reinforced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_memories',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'namespace', 'is_active'], name='memory_user_namespace_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'namespace', 'key'), name='uniq_user_memory_key'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='memory_confidence_0_1')],
            },
        ),
        migrations.AddIndex(
            model_name='assistantsuggestion',
            index=models.Index(fields=['user', 'status', '-interruption_priority'], name='suggest_user_status_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantsuggestion',
            index=models.Index(fields=['user', 'scheduled_for'], name='suggest_user_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantsuggestion',
            constraint=models.UniqueConstraint(fields=('user', 'deduplication_key'), name='uniq_user_suggestion_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='assistantsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('interruption_priority__gte', 0), ('interruption_priority__lte', 100)), name='suggest_priority_0_100'),
        ),
        migrations.AddIndex(
            model_name='suggestionfeedback',
            index=models.Index(fields=['user', 'feedback_type', '-occurred_at'], name='feedback_user_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionhistory',
            index=models.Index(fields=['user', '-occurred_at'], name='suggest_hist_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['user', 'behavior_type', '-occurred_at'], name='behavior_user_type_time_idx'),
        ),
    ]
